apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-api-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: node-api
  template:
    metadata:
      labels:
        app: node-api
    spec:
      containers:
        - name: node-api
          image: # Replace with your actual image (e.g., from Docker Hub)
          ports:
            - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: node-api-service
spec:
  type: LoadBalancer
  selector:
    app: node-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000